#!/bin/ruby

require_relative "token_generator"

puts "Starting..."

command = ARGV[0]
case command
when "get-token"
  TokenGenerator.new(
    client_id: ENV["SPOTIFY_CLIENT_ID"],
    client_secret: ENV["SPOTIFY_CLIENT_SECRET"],
    refresh_token: ENV["SPOTIFY_REFRESH_TOKEN"],
  ).generate
when "get-fresh-token"
  TokenGenerator.new(
    client_id: ENV["SPOTIFY_CLIENT_ID"],
    client_secret: ENV["SPOTIFY_CLIENT_SECRET"],
  ).generate
else
  puts "Unknown command \"#{command}\""
end
